---
title: "L01 Review"
subtitle: "Data Science 3 with R (STAT 301-3)"
author: "Harin Jeong"
pagetitle: "L01 Harin Jeong"
date: today

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-location: left
    embed-resources: true
    code-fold: false
    link-external-newwindow: true

execute:
  warning: false

from: markdown+emoji
reference-location: margin
citation-location: margin   
---

::: {.callout-tip icon="false"}
## Github Repo Link

To link to your github **repo**sitory, appropriately edit the example link below. Meaning replace `https://your-github-repo-url` with your github repo url. Suggest verifying the link works before submitting.

[Jeong Github Link](https://github.com/stat301-3-2026-spring/l01-review-harin-jeong)
:::

## Overview

The goal of this lab is to review machine learning/predictive modeling vocabulary and concepts covered in Data Science 2 with R (STAT 301-2).

## Questions

When completing the following questions ensure your solutions are neatly formatted and clearly indicated. Consider including diagrams/images in some of your solutions, if it helps to make things easier to describe/discuss.

### Question 1 :white_check_mark:

Provide a brief outline/overview of the steps involved in a supervised machine learning process. Could provide this as a bulleted list. 

::: {.callout-tip icon="false"}
## Solution

1. Defining the problem
2. Data collection
3. Data cleaning
4. Exploratory data analysis
5. Splitting the data
6. Preprocessing/Feature engineering
7. Choosing a model
8. Training the model 
9. Tuning hyperparameters
10. Evaluating on the test set
11. Final model 

:::

### Question 2 :white_check_mark:

Explain the difference between supervised and unsupervised learning.

::: {.callout-tip icon="false"}
## Solution

Supervised learning involves labeled data with a target variable. Unsupervised learning uses unlabeled data without predefined outputs. It is used to uncover new insights, such as patterns, structures, or relationships, about the data.

:::

### Question 3 :white_check_mark:

In general, we can classify a model by its purpose into 1 of the 3 categories below. Provide a brief description of the goals of these model classes.

#### Descriptive Models 

::: {.callout-tip icon="false"}
## Solution

Descriptive models seek to describe certain characteristics of a dataset, and visually emphasize a trend or artifact of the data. 

:::

#### Inferential Models

::: {.callout-tip icon="false"}
## Solution

Inferential models produce a decision for a research question or test a hypothesis, relying on underlying assumptions.  

:::

#### Predictive Models

::: {.callout-tip icon="false"}
## Solution

Predictive models aim for the most accurate prediction possible for new data. 

:::

### Question 4 :white_check_mark:

We can further describe/classify predictive models by how they were derived or developed as being either mechanistic or empirically driven. 

#### Part (a)

What does it mean to be a mechanistic model?

::: {.callout-tip icon="false"}
## Solution

Mechanistic models depend on known, fundamental laws. They are formula-/theory-based. 

:::

#### Part (b)

What does it mean to be an empirically driven model?

::: {.callout-tip icon="false"}
## Solution

Empirically driven models rely on observed data. 

:::

#### Part (c)

How does the mechanistic and empirically driven model terminology relate to the parametric and nonparametric model terminology? 

::: {.callout-tip icon="false"}
## Solution

Mechanistic models are parametric. Empirically driven models are nonparametric. 

:::

#### Part (d)

In general, is a mechanistic or empirically driven model easier to interpret? Explain.

::: {.callout-tip icon="false"}
## Solution

In general, mechanistic models are easier to interpret than empirically driven models because mechanistic models are based on known laws, so the relationships in these models represent real cause-and-effect mechanisms. Empirically driven models are based mainly on patterns in data and often do not show how or why the relationships occur. 

:::

#### Part (e)

How does mechanistic and empirically driven model terminology relate to the idea of model flexibility? That is, which would be more or less flexible than the other.

::: {.callout-tip icon="false"}
## Solution

Mechanistic models tend to have lower flexibility and empirically driven models tend to have higher flexibility. 

:::

#### Part (f)

Describe the bias-variance trade-off when considering the use of a mechanistic or empirically driven model. 

::: {.callout-tip icon="false"}
## Solution

Mechanistic models have high bias and low variance, whereas empirically driven models have low bias and high variance. 

:::

### Question 5 :white_check_mark: 

Explain the difference between a regression and classification machine learning (ML) problems.

::: {.callout-tip icon="false"}
## Solution

Regression problems predict continuous outcomes, whereas classification problems predict categorical outcomes. 

:::

### Question 6 :white_check_mark:

When splitting the data, why is it useful to stratify by the outcome/target variable? 

::: {.callout-tip icon="false"}
## Solution

Stratifying by the outcome variable ensures that each data split has a similar distribution of the target variable. This is especially important if some outcome groups are rare, because without stratification one split might end up with too many or too few of a certain group, making the model train poorly or be evaluated unfairly. 

:::

### Question 7 :white_check_mark:

Briefly describe how v-fold cross validation with repeats is used to estimate test RMSE. Also provide an explanation of why we use it. 

::: {.callout-tip icon="false"}
## Solution

V-fold cross validation with repeats works by splitting the training data into v groups, training the model on v−1 groups, and testing it on the remaining group. This process is repeated so each fold is used as the test set, and then the whole process is repeated multiple times with different splits. The RMSE from all runs is averaged to estimate the test RMSE. This method is used for a more reliable estimate of model performance and too reduce the effect of random chance from one data split.

:::

### Question 8 :white_check_mark:

When might we use a bootstrap resampling procedure instead of v-fold cross validation to estimate test RMSE?

::: {.callout-tip icon="false"}
## Solution

We might use a bootstrap resampling procedure instead of v-fold cross validation when the dataset is small. Bootstrapping repeatedly samples from the data with replacement to create many training sets, allowing us to estimate test RMSE even when we don’t have much data to split into folds. This method makes more efficient use of limited data because each bootstrap sample uses most of the observations for training. It is especially useful when we want a stable estimate of model performance with small sample sizes.

:::

### Question 9 

Briefly describe model tuning and why we use it.

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

### Question 10 

What are two common performance metrics when dealing with a regression ML problem?

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

What are two common performance metrics when dealing with a classification ML problem?

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

### Question 11

Classify each question/problem below as either prediction or inferential. Explain your reasoning for each.

A company with a subscription based service (for example Netflix, Disney+, New York Times, etc) has data concerning customer interactions with a them, including features like the number of customer service calls, quality of service calls, subscription length, engagement with the service, discounted service, etc. They are interested in two questions:

1. Does a high number of service calls impact a customer's likelihood of churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

2. How likely is it that a customer will churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

